import './styles/global.css';
import { acronym, guardian } from './styles/typography';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${acronym.variable} ${guardian.variable} font-guardian`}>{children}</body>
    </html>
  );
}
